---
- name: add things we need to server
  hosts: localhost
  remote_user: root

  tasks:
  - name: install packages
    yum: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - python3

  - hosts: renderfarm
    roles:
       - victorklos.install-blender
