---
- name: add things we need to server
  hosts: localhost
  remote_user: root
  become: true

  tasks:
  - name: Install the latest version of Packages
    yum:
      name:
        - git
        - python3
        - wget
        - xz
        - blender
      state: latest

#  - name: unisntall stuf
#    yum:
#      name:
#      - nginx
#      - postgresql
#      - postgresql-server
#      state: absent

#  - name: install blender cli
#    roles:
#      - roles.renderfarm
