---
- name: add things we need to server
  hosts: localhost
  remote_user: root
  become: true

  tasks:
  - name: Install the latest version of git
    yum:
      name:
        - git
  - name: Install the latest version of python
    yum:
      name:
        - python3
  - name: Install the latest version of wget
    yum:
      name:
        - wget
  - name: Install the latest version of xz
    yum:
      name:
        - xz
  - name: Install the latest version of blender
    yum:
      name:
        - blender
      state: latest
  - name: clone github repo
    shell: git clone https://github.com/Blender-Render-Farm/blender-render-farm.git
  - name: Install virtualenv
    pip: 
      name: virtualenv

  - name: Install requirements.txt
    pip: 
      requirements: ~/blender-render-farm/requirements.txt
      virtualenv: ~/blender-render-app
      

#  - name: unisntall stuf
#    yum:
#      name:
#      - nginx
#      - postgresql
#      - postgresql-server
#      state: absent

#  - name: install blender cli
#    roles:
#      - roles.renderfarm
